### ISSUE TITLE
Custom defaultLocale like en instead of en_US?

### ISSUE THREAD

**Issue by fritx** [sindresorhus/os-locale#23]
https://github.com/sindresorhus/os-locale/blob/master/index.js#L7

```js
const defaultLocale = 'en_US';
```

Could we provide a custom defaultLocale like `en`?

Motivations:

```js
navigator.languages
// ["en", "zh-CN", "zh", "zh-TW", "ja"]
```

```plain
$ ls 0.18.8-sdk/osx64/nwjs.app/Contents/Resources/ | grep en
> document.icns
en.lproj
en_GB.lproj
```

**Comment by sindresorhus** [comment]
`en_US` is the default fallback since that's what `$ locale` returns on US systems. Say we provided such option, it would still not match `en` for anyone on a US system, only when the locale can't be detected.

You listed your motivations as examples, but not what problem you're actually trying to solve. These things use different locale identifiers.

**Comment by fritx** [comment]
Anyway thanks for your reply ;)

Btw, I've found that PATH of wmic is missing in one of my colleagues's Windows machine.
And I guess I have some solution though.

https://github.com/nwjs/nw-builder/issues/357
